#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

define('SPOOL_CRONTABS_START', microtime(true));
define('BASE_PATH', __DIR__);

require __DIR__ . '/vendor/autoload.php';

$app = new Application('Spool-Crontabs', 'v0.0.1');
$app->register('start')
    ->addArgument('start', InputArgument::OPTIONAL, 'input you name')
    ->setDescription('')
    ->setHelp('spool')
    ->setCode(
        function (InputInterface $input, OutputInterface $output) {
            $name = $input->getArgument('start');
            $message = 'hello: ' . $name . ' ' . BASE_PATH . env('sss');
            $output->writeln('<info>' . $message . '</info>');
        }
    );
$app->run();
